name: socials_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  freezed: ^3.2.3
  intl: ^0.20.2
  injectable: ^2.5.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.2.1
  dartz: ^0.10.1
  carousel_slider: ^5.1.1
  image_picker: ^1.2.0
  auto_route: ^10.1.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  permission_handler: ^12.0.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.4.2
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1
  easy_localization: ^3.0.8
  pinput: ^5.0.2
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.2
  percent_indicator: ^4.2.5
  shorebird_code_push: ^2.0.5
  firebase_analytics: ^12.0.3
  sentry_flutter: ^9.7.0
  connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator:
  injectable_generator:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
